[env]
TERM = "xterm-256color"

[general]
import = [
  "~/.config/alacritty/themes/catppuccin-mocha.toml"
]

[window]
padding = { x = 10, y = 10 }
opacity = 0.85
blur = true

[font]
size = 8

[cursor]
style = { blinking = "Always" }

[selection]
save_to_clipboard = true
